In [197]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [198]:
train_df = pd.read_csv('../train/train_user.csv', encoding='utf-8')
test_df = pd.read_csv('../test/test_user.csv', encoding = 'utf-8')

In [199]:
train_df['exist_null'] = train_df['arpu_202003'].isnull().astype(np.int64)
test_df['exist_null'] = test_df['arpu_202004'].isnull().astype(np.int64)

In [200]:
train_df['_arpu'] = train_df['arpu_202003']
test_df['_arpu'] = test_df['arpu_202004']

In [201]:
df = pd.concat([train_df,test_df], axis = 0).reset_index(drop = True)

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [202]:
df

,_arpu,arpu_201908,arpu_201909,arpu_201910,arpu_201911,arpu_201912,arpu_202001,arpu_202002,arpu_202003,arpu_202004,city_name,county_name,exist_null,idcard_cnt,label,phone_no_m
0,45.0,46.06,45.00,45.0,45.00,45.00,45.0,45.0,45.0,NaN,绵阳,江油分公司,0,1,0.0,672ddbf02a5544d32e4ecc9433b1981bffe23bf912273a...
1,60.0,79.00,79.20,79.1,79.30,41.40,34.1,59.4,60.0,NaN,德阳,旌阳分公司,0,1,0.0,5e1272273e041e82cb275ae877710be98cdaf5b0a8f34d...
2,63.0,18.85,24.45,22.0,21.40,22.15,21.1,61.3,63.0,NaN,成都,金堂分公司,0,2,0.0,eaab3472ec87b076e69e6e8bb62b14341638fc63661a6c...
3,23.2,19.20,29.65,130.4,173.12,19.00,19.0,19.0,23.2,NaN,成都,高新分公司,0,2,0.0,0ce1bb415704178bf44e9c9b431a39b083a132c8e6d99f...
4,50.0,50.00,50.00,50.0,50.00,50.00,50.0,50.0,50.0,NaN,德阳,旌阳分公司,0,1,0.0,28b87f35f63f65096a53e3a4c97eaffd4a6c43ffa7e92d...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8146,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,绵阳,三台分公司,0,1,NaN,b544be7faeb565e3b25b2624121b6fbb188dd783304054...
8147,62.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.0,雅安,石棉分公司,0,1,NaN,8f8220d7b20f8a7d92a443c97f2276b4d62f7d058cb172...
8148,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,自贡,自井分公司,0,1,NaN,2390f521ad86b31fa73e8e6395817a8c447ce077796c79...
8149,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0,自贡,贡井分公司,0,5,NaN,15a2d650f7a7a24b3e8dfdd5e59dc251cb3043f290fcaf...
8150,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.1,绵阳,江油分公司,0,1,NaN,08923b36132be7e0e4739794aa9af2c4ca896dc789e320...

In [203]:
df['_arpu'] = np.max(df.iloc[:,1:10], axis = 1)
# df.drop(df.columns[:9],axis = 1, inplace=True)

In [204]:
# df['arpu_null'] = df['_arpu'].isnull().astype(np.int32)
df['arpu_high'] = (df['_arpu']>500).astype(np.int64)

In [205]:
cat_features = ['city_name','county_name']
df[cat_features] = df[cat_features].fillna('缺失')
# Label Encoding
# le = LabelEncoder()
# for feature in cat_features:
#     df[feature] = le.fit_transform(df[feature])
    
## Onehot Encoding
df = pd.concat([df,pd.get_dummies(df[cat_features])],axis=1)
df.drop(cat_features, axis = 1, inplace = True)

In [206]:
df.head()

,_arpu,arpu_201908,arpu_201909,arpu_201910,arpu_201911,arpu_201912,arpu_202001,arpu_202002,arpu_202003,arpu_202004,...,county_name_顺庆分公司,county_name_马尔康县分公司,county_name_马边分公司,county_name_高县分公司,county_name_高坪分公司,county_name_高新分公司,county_name_高新区分公司,county_name_高新西区分公司,county_name_龙泉驿分公司,county_name_龙马潭分公司
0,46.06,46.06,45.00,45.0,45.00,45.00,45.0,45.0,45.0,NaN,...,0,0,0,0,0,0,0,0,0,0
1,79.30,79.00,79.20,79.1,79.30,41.40,34.1,59.4,60.0,NaN,...,0,0,0,0,0,0,0,0,0,0
2,63.00,18.85,24.45,22.0,21.40,22.15,21.1,61.3,63.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3,173.12,19.20,29.65,130.4,173.12,19.00,19.0,19.0,23.2,NaN,...,0,0,0,0,0,1,0,0,0,0
4,50.00,50.00,50.00,50.0,50.00,50.00,50.0,50.0,50.0,NaN,...,0,0,0,0,0,0,0,0,0,0

In [207]:
voc_df = pd.read_csv('./voc_submit.csv', encoding = 'utf-8')
sms_df = pd.read_csv('./sms_submit.csv', encoding = 'utf-8')
app_df = pd.read_csv('./app_submit.csv', encoding = 'utf-8')

In [208]:
voc_df.head()

,phone_no_m,voc_opposite_count,voc_opposite_unique,voc_opposite_mean,voc_opposite_max,voc_calltype_1,voc_imeis,voc_calltype1_per_oppo,voc_city_unique,voc_county_unique,...,voc_county_马尔康县,voc_county_马边彝族自治县,voc_county_高县,voc_county_高坪区,voc_county_高新区,voc_county_高新南区,voc_county_高新西区,voc_county_黑水县,voc_county_龙泉驿区,voc_county_龙马潭区
0,b8758a7e6a4834bd69444ef669a5bb21a8b352d0a47590...,65,59,1.101695,3,65.0,1.0,1.000000,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
1,b6cd606931ba69138706e76f1bb691c13ae2916ddb2a2d...,1,1,1.000000,1,1.0,1.0,1.000000,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
2,cb0e22e4e913a1e935eed6b4c00d2305da8762e462c032...,3,2,1.500000,2,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,dd9a249f029226a2fffbf92c6aae809182068e3743534a...,19,8,2.375000,7,1.0,1.0,0.052632,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0
4,8b2a6d4b83d36e8f9169ad8d34fab9a10f23e0d6c610a3...,264,239,1.104603,9,264.0,3.0,1.000000,1.0,1.0,...,0,0,0,0,0,0,0,0,0,0

In [209]:
sms_df.head()

,phone_no_m,sms_count,sms_nunique,sms_rate,calltype_2,calltype_rate,hour_mode,hour_mode_count,hour_nunique,day_mode,...,sms_hour_mode_count,sms_hour_count,sms_hour_kurt,sms_hour_skew,sms_day_mode,sms_day_mode_count,sms_day_count,sms_day_kurt,sms_day_skew,sms_call_called_rate
0,30fff49d3fbf020411af17c84ee2912a0bfd9e3036e50a...,2,2,1.000000,1.0,0.500000,10,2,1,19,...,2,1,NaN,NaN,19,2,1,NaN,NaN,1.000000
1,80d5353ac17cab91ddb0c1f8d3aec1e84420699230a800...,14,5,2.800000,14.0,1.000000,13,10,2,9,...,10,2,-1.034091,1.066536,9,14,1,0.000000,0.000000,0.066667
2,59226c0b70f4c51943dac2f079caa0696cb8eb5007cbd9...,313,101,3.099010,307.0,0.980831,16,253,10,5,...,253,10,5.071479,-2.246892,5,250,6,3.920106,-0.915138,0.022727
3,8f1967131ee7fcadf1ab7a3dfb1a933ea4b1c4e16236c1...,89,10,8.900000,89.0,1.000000,14,26,4,11,...,26,4,1.193921,1.656642,11,89,1,0.000000,0.000000,0.011111
4,a4e9f46eebdcc7cb30e1e5b8fe79f27d99a286163ff810...,25,3,8.333333,23.0,0.920000,13,9,4,8,...,9,4,-1.731625,-0.051061,8,18,3,0.980858,-0.047329,0.125000

In [210]:
app_df.head()

,phone_no_m,flow,app_count,flow_null,flow_min,flow_mean,flow_max,flow_per_month,flow_per_app,微信,...,新东方在线官网,天极网,QiCheBaoJiaDaQuan,联想手机商城,Trafficmanager,ZhongYangTianQiYuBao,Samqaicongen,11H5,西瓜视频,ShaYuJiZhang
0,00073ceecc0f7220a440580ac5dea410c90d14b6669458...,7794.011783,95,0,0.000072,31.427467,3163.689316,1113.430255,81.187623,1,...,0,0,0,0,0,0,0,0,0,0
1,00086f1d2e2c1227f811c3e17f2e9c37cf9971f47bb933...,108.340788,24,0,0.000220,4.166953,102.223318,108.340788,4.333632,1,...,0,0,0,0,0,0,0,0,0,0
2,000c00db8809c27e723ba90582bf334b2d3ca9063f53fb...,0.000000,0,1,0.000000,0.000000,0.000000,0.000000,0.000000,0,...,0,0,0,0,0,0,0,0,0,0
3,000f0f3100d815774e51f504a43e636dee84449da1c2c4...,3105.527115,198,0,0.001053,13.271483,1122.193042,3105.527115,15.605664,1,...,0,0,0,0,0,0,0,0,0,0
4,001285c54745996ac4705eca7713d73de7921edf4133a6...,0.000000,0,1,0.000000,0.000000,0.000000,0.000000,0.000000,0,...,0,0,0,0,0,0,0,0,0,0

In [211]:
df = pd.merge(df, voc_df, how = 'left',on = 'phone_no_m')
df = pd.merge(df, sms_df, how = 'left',on = 'phone_no_m')
df = pd.merge(df, app_df, how = 'left',on = 'phone_no_m')

In [212]:
null_feature = df.columns[df.isnull().any()].tolist()
for feature in null_feature:
    df[feature].fillna(0, inplace = True)

In [213]:
df.drop(['phone_no_m'],axis = 1,inplace = True)

In [215]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
for feature in df.columns:
    df[feature] = scaler.fit_transform(np.array(df[feature]).reshape(-1,1))

In [216]:
train_df = df.iloc[:len(train_df),:]
test_df = df.iloc[len(train_df):,:]

In [217]:
## 特征工程之后的训练集和测试集导出
train_df.to_csv('./train_df.csv', encoding='utf-8',index = None)
test_df.to_csv('./test_df.csv', encoding='utf-8', index = None)

In [218]:
train_df['label'].describe()

count    6106.000000
mean        0.321323
std         0.467023
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000
Name: label, dtype: float64

In [219]:
train_df.head()

,_arpu,arpu_201908,arpu_201909,arpu_201910,arpu_201911,arpu_201912,arpu_202001,arpu_202002,arpu_202003,arpu_202004,...,新东方在线官网,天极网,QiCheBaoJiaDaQuan,联想手机商城,Trafficmanager,ZhongYangTianQiYuBao,Samqaicongen,11H5,西瓜视频,ShaYuJiZhang
0,0.009059,0.090923,0.114849,0.034855,0.023405,0.052118,0.034728,0.003798,0.012848,0.014537,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.011850,0.155948,0.156400,0.061267,0.041246,0.050237,0.026316,0.005013,0.016127,0.014537,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.010482,0.037210,0.089882,0.017040,0.011131,0.040178,0.016283,0.005174,0.016783,0.014537,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.019727,0.037901,0.096200,0.101002,0.090043,0.038532,0.014663,0.001604,0.008083,0.014537,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.009390,0.098701,0.120924,0.038728,0.026006,0.054731,0.038586,0.004220,0.013941,0.014537,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [220]:
import xgboost as xgb
from xgboost import plot_importance
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [221]:
train_x, val_x, train_y, val_y = train_test_split(train_df.drop(['label'], axis = 1), train_df['label'], test_size = 0.1, random_state = 777)

In [222]:
dtrain = xgb.DMatrix(train_x,label=train_y)
dval =xgb.DMatrix(val_x, label = val_y)

In [231]:
params = {'booster':'gbtree',
         'objective':'binary:logistic',
         'eval_metric':'auc',
         'max_depth':3,
         'min_child_weight':1,########
         'gamma':6,
         'subsample':0.8,
         
         'colsample_bytree':0.9,
         'colsample_bylevel':0.8,
         'lambda':1,
         'eta':0.1,
         'tree_method':'exact',
         'seed':72,
         'nthread':4,
         'scale_pos_weight': 3
         }

In [232]:
###调参用
# for i in np.arange(1,11):
#     params['gamma'] = i
#     model = xgb.train(params,dtrain,evals = watchlist,early_stopping_rounds=100,num_boost_round=10000,verbose_eval=False)
#     y_pred_pro = model.predict(dval)
#     p, f1 = best_f1(val_y, y_pred_pro)
#     print(i, f1)

In [233]:
watchlist = [(dtrain,'train'),(dval, 'eval')]

In [234]:
model = xgb.train(params,dtrain,evals = watchlist,early_stopping_rounds=100,num_boost_round=10000)

[0]	train-auc:0.91218	eval-auc:0.92054
Multiple eval metrics have been passed: 'eval-auc' will be used for early stopping.

Will train until eval-auc hasn't improved in 100 rounds.
[1]	train-auc:0.93351	eval-auc:0.93854
[2]	train-auc:0.93598	eval-auc:0.94337
[3]	train-auc:0.94416	eval-auc:0.94767
[4]	train-auc:0.94702	eval-auc:0.94926
[5]	train-auc:0.94997	eval-auc:0.94980
[6]	train-auc:0.95204	eval-auc:0.95104
[7]	train-auc:0.95337	eval-auc:0.95068
[8]	train-auc:0.95442	eval-auc:0.95109
[9]	train-auc:0.95502	eval-auc:0.95246
[10]	train-auc:0.95559	eval-auc:0.95268
[11]	train-auc:0.95688	eval-auc:0.95401
[12]	train-auc:0.95744	eval-auc:0.95390
[13]	train-auc:0.95830	eval-auc:0.95582
[14]	train-auc:0.95898	eval-auc:0.95587
[15]	train-auc:0.95972	eval-auc:0.95627
[16]	train-auc:0.96054	eval-auc:0.95696
[17]	train-auc:0.96128	eval-auc:0.95836
[18]	train-auc:0.96196	eval-auc:0.95877
[19]	train-auc:0.96221	eval-auc:0.95928
[20]	train-auc:0.96249	eval-auc:0.95964
[21]	train-auc:0.96286	eval-auc:0.96002
[22]	train-auc:0.96334	eval-auc:0.96018
[23]	train-auc:0.96367	eval-auc:0.96065
[24]	train-auc:0.96449	eval-auc:0.95976
[25]	train-auc:0.96470	eval-auc:0.96004
[26]	train-auc:0.96524	eval-auc:0.96013
[27]	train-auc:0.96578	eval-auc:0.95937
[28]	train-auc:0.96600	eval-auc:0.96009
[29]	train-auc:0.96635	eval-auc:0.96018
[30]	train-auc:0.96666	eval-auc:0.96031
[31]	train-auc:0.96688	eval-auc:0.96057
[32]	train-auc:0.96702	eval-auc:0.96073
[33]	train-auc:0.96746	eval-auc:0.96088
[34]	train-auc:0.96786	eval-auc:0.96070
[35]	train-auc:0.96809	eval-auc:0.96002
[36]	train-auc:0.96843	eval-auc:0.96027
[37]	train-auc:0.96873	eval-auc:0.96076
[38]	train-auc:0.96900	eval-auc:0.96060
[39]	train-auc:0.96941	eval-auc:0.96102
[40]	train-auc:0.96981	eval-auc:0.96108
[41]	train-auc:0.97038	eval-auc:0.96175
[42]	train-auc:0.97052	eval-auc:0.96201
[43]	train-auc:0.97070	eval-auc:0.96188
[44]	train-auc:0.97113	eval-auc:0.96180
[45]	train-auc:0.97155	eval-auc:0.96137
[46]	train-auc:0.97220	eval-auc:0.96132
[47]	train-auc:0.97227	eval-auc:0.96179
[48]	train-auc:0.97274	eval-auc:0.96155
[49]	train-auc:0.97345	eval-auc:0.96161
[50]	train-auc:0.97389	eval-auc:0.96177
[51]	train-auc:0.97404	eval-auc:0.96201
[52]	train-auc:0.97442	eval-auc:0.96227
[53]	train-auc:0.97457	eval-auc:0.96198
[54]	train-auc:0.97490	eval-auc:0.96197
[55]	train-auc:0.97526	eval-auc:0.96217
[56]	train-auc:0.97568	eval-auc:0.96219
[57]	train-auc:0.97598	eval-auc:0.96264
[58]	train-auc:0.97618	eval-auc:0.96253
[59]	train-auc:0.97637	eval-auc:0.96315
[60]	train-auc:0.97695	eval-auc:0.96265
[61]	train-auc:0.97715	eval-auc:0.96288
[62]	train-auc:0.97743	eval-auc:0.96315
[63]	train-auc:0.97775	eval-auc:0.96271
[64]	train-auc:0.97800	eval-auc:0.96288
[65]	train-auc:0.97831	eval-auc:0.96255
[66]	train-auc:0.97864	eval-auc:0.96233
[67]	train-auc:0.97886	eval-auc:0.96233
[68]	train-auc:0.97911	eval-auc:0.96244
[69]	train-auc:0.97922	eval-auc:0.96263
[70]	train-auc:0.97953	eval-auc:0.96250
[71]	train-auc:0.97992	eval-auc:0.96203
[72]	train-auc:0.98009	eval-auc:0.96225
[73]	train-auc:0.98042	eval-auc:0.96201
[74]	train-auc:0.98064	eval-auc:0.96178
[75]	train-auc:0.98103	eval-auc:0.96198
[76]	train-auc:0.98142	eval-auc:0.96206
[77]	train-auc:0.98171	eval-auc:0.96180
[78]	train-auc:0.98213	eval-auc:0.96200
[79]	train-auc:0.98230	eval-auc:0.96183
[80]	train-auc:0.98253	eval-auc:0.96198
[81]	train-auc:0.98282	eval-auc:0.96227
[82]	train-auc:0.98294	eval-auc:0.96208
[83]	train-auc:0.98329	eval-auc:0.96243
[84]	train-auc:0.98344	eval-auc:0.96242
[85]	train-auc:0.98351	eval-auc:0.96228
[86]	train-auc:0.98389	eval-auc:0.96213
[87]	train-auc:0.98413	eval-auc:0.96230
[88]	train-auc:0.98460	eval-auc:0.96254
[89]	train-auc:0.98479	eval-auc:0.96238
[90]	train-auc:0.98507	eval-auc:0.96257
[91]	train-auc:0.98536	eval-auc:0.96232
[92]	train-auc:0.98555	eval-auc:0.96239
[93]	train-auc:0.98561	eval-auc:0.96221
[94]	train-auc:0.98591	eval-auc:0.96217
[95]	train-auc:0.98596	eval-auc:0.96225
[96]	train-auc:0.98600	eval-auc:0.96229
[97]	train-auc:0.98629	eval-auc:0.96218
[98]	train-auc:0.98654	eval-auc:0.96230
[99]	train-auc:0.98678	eval-auc:0.96257
[100]	train-auc:0.98694	eval-auc:0.96286
[101]	train-auc:0.98706	eval-auc:0.96302
[102]	train-auc:0.98716	eval-auc:0.96297
[103]	train-auc:0.98726	eval-auc:0.96316
[104]	train-auc:0.98741	eval-auc:0.96335
[105]	train-auc:0.98753	eval-auc:0.96315
[106]	train-auc:0.98777	eval-auc:0.96302
[107]	train-auc:0.98799	eval-auc:0.96304
[108]	train-auc:0.98803	eval-auc:0.96299
[109]	train-auc:0.98813	eval-auc:0.96304
[110]	train-auc:0.98825	eval-auc:0.96320
[111]	train-auc:0.98848	eval-auc:0.96301
[112]	train-auc:0.98862	eval-auc:0.96289
[113]	train-auc:0.98874	eval-auc:0.96269
[114]	train-auc:0.98897	eval-auc:0.96268
[115]	train-auc:0.98912	eval-auc:0.96253
[116]	train-auc:0.98925	eval-auc:0.96234
[117]	train-auc:0.98934	eval-auc:0.96255
[118]	train-auc:0.98943	eval-auc:0.96279
[119]	train-auc:0.98954	eval-auc:0.96316
[120]	train-auc:0.98982	eval-auc:0.96352
[121]	train-auc:0.98994	eval-auc:0.96337
[122]	train-auc:0.98997	eval-auc:0.96344
[123]	train-auc:0.99020	eval-auc:0.96307
[124]	train-auc:0.99034	eval-auc:0.96310
[125]	train-auc:0.99048	eval-auc:0.96335
[126]	train-auc:0.99057	eval-auc:0.96338
[127]	train-auc:0.99080	eval-auc:0.96328
[128]	train-auc:0.99088	eval-auc:0.96316
[129]	train-auc:0.99096	eval-auc:0.96289
[130]	train-auc:0.99114	eval-auc:0.96286
[131]	train-auc:0.99121	eval-auc:0.96299
[132]	train-auc:0.99135	eval-auc:0.96323
[133]	train-auc:0.99141	eval-auc:0.96315
[134]	train-auc:0.99144	eval-auc:0.96310
[135]	train-auc:0.99157	eval-auc:0.96314
[136]	train-auc:0.99169	eval-auc:0.96306
[137]	train-auc:0.99179	eval-auc:0.96322
[138]	train-auc:0.99186	eval-auc:0.96316
[139]	train-auc:0.99196	eval-auc:0.96310
[140]	train-auc:0.99209	eval-auc:0.96325
[141]	train-auc:0.99218	eval-auc:0.96312
[142]	train-auc:0.99239	eval-auc:0.96317
[143]	train-auc:0.99245	eval-auc:0.96323
[144]	train-auc:0.99257	eval-auc:0.96351
[145]	train-auc:0.99270	eval-auc:0.96325
[146]	train-auc:0.99277	eval-auc:0.96336
[147]	train-auc:0.99286	eval-auc:0.96332
[148]	train-auc:0.99293	eval-auc:0.96321
[149]	train-auc:0.99295	eval-auc:0.96344
[150]	train-auc:0.99301	eval-auc:0.96349
[151]	train-auc:0.99313	eval-auc:0.96289
[152]	train-auc:0.99322	eval-auc:0.96291
[153]	train-auc:0.99330	eval-auc:0.96274
[154]	train-auc:0.99341	eval-auc:0.96261
[155]	train-auc:0.99341	eval-auc:0.96250
[156]	train-auc:0.99350	eval-auc:0.96247
[157]	train-auc:0.99355	eval-auc:0.96245
[158]	train-auc:0.99360	eval-auc:0.96244
[159]	train-auc:0.99369	eval-auc:0.96260
[160]	train-auc:0.99382	eval-auc:0.96266
[161]	train-auc:0.99401	eval-auc:0.96263
[162]	train-auc:0.99404	eval-auc:0.96244
[163]	train-auc:0.99415	eval-auc:0.96249
[164]	train-auc:0.99428	eval-auc:0.96252
[165]	train-auc:0.99435	eval-auc:0.96248
[166]	train-auc:0.99439	eval-auc:0.96258
[167]	train-auc:0.99445	eval-auc:0.96275
[168]	train-auc:0.99452	eval-auc:0.96274
[169]	train-auc:0.99457	eval-auc:0.96274
[170]	train-auc:0.99457	eval-auc:0.96273
[171]	train-auc:0.99463	eval-auc:0.96260
[172]	train-auc:0.99465	eval-auc:0.96254
[173]	train-auc:0.99474	eval-auc:0.96261
[174]	train-auc:0.99477	eval-auc:0.96259
[175]	train-auc:0.99485	eval-auc:0.96260
[176]	train-auc:0.99487	eval-auc:0.96283
[177]	train-auc:0.99489	eval-auc:0.96274
[178]	train-auc:0.99495	eval-auc:0.96254
[179]	train-auc:0.99499	eval-auc:0.96268
[180]	train-auc:0.99509	eval-auc:0.96275
[181]	train-auc:0.99514	eval-auc:0.96288
[182]	train-auc:0.99524	eval-auc:0.96297
[183]	train-auc:0.99529	eval-auc:0.96311
[184]	train-auc:0.99537	eval-auc:0.96301
[185]	train-auc:0.99545	eval-auc:0.96304
[186]	train-auc:0.99553	eval-auc:0.96296
[187]	train-auc:0.99556	eval-auc:0.96301
[188]	train-auc:0.99565	eval-auc:0.96281
[189]	train-auc:0.99572	eval-auc:0.96289
[190]	train-auc:0.99575	eval-auc:0.96294
[191]	train-auc:0.99574	eval-auc:0.96299
[192]	train-auc:0.99577	eval-auc:0.96304
[193]	train-auc:0.99579	eval-auc:0.96307
[194]	train-auc:0.99588	eval-auc:0.96306
[195]	train-auc:0.99592	eval-auc:0.96297
[196]	train-auc:0.99592	eval-auc:0.96309
[197]	train-auc:0.99593	eval-auc:0.96302
[198]	train-auc:0.99598	eval-auc:0.96312
[199]	train-auc:0.99598	eval-auc:0.96326
[200]	train-auc:0.99604	eval-auc:0.96341
[201]	train-auc:0.99605	eval-auc:0.96335
[202]	train-auc:0.99611	eval-auc:0.96316
[203]	train-auc:0.99625	eval-auc:0.96327
[204]	train-auc:0.99626	eval-auc:0.96330
[205]	train-auc:0.99627	eval-auc:0.96326
[206]	train-auc:0.99631	eval-auc:0.96344
[207]	train-auc:0.99636	eval-auc:0.96331
[208]	train-auc:0.99634	eval-auc:0.96349
[209]	train-auc:0.99643	eval-auc:0.96361
[210]	train-auc:0.99647	eval-auc:0.96368
[211]	train-auc:0.99653	eval-auc:0.96379
[212]	train-auc:0.99655	eval-auc:0.96364
[213]	train-auc:0.99657	eval-auc:0.96368
[214]	train-auc:0.99662	eval-auc:0.96353
[215]	train-auc:0.99662	eval-auc:0.96353
[216]	train-auc:0.99662	eval-auc:0.96353
[217]	train-auc:0.99669	eval-auc:0.96372
[218]	train-auc:0.99669	eval-auc:0.96363
[219]	train-auc:0.99674	eval-auc:0.96353
[220]	train-auc:0.99678	eval-auc:0.96348
[221]	train-auc:0.99686	eval-auc:0.96347
[222]	train-auc:0.99686	eval-auc:0.96347
[223]	train-auc:0.99692	eval-auc:0.96356
[224]	train-auc:0.99694	eval-auc:0.96374
[225]	train-auc:0.99699	eval-auc:0.96388
[226]	train-auc:0.99709	eval-auc:0.96403
[227]	train-auc:0.99710	eval-auc:0.96403
[228]	train-auc:0.99711	eval-auc:0.96403
[229]	train-auc:0.99711	eval-auc:0.96408
[230]	train-auc:0.99714	eval-auc:0.96418
[231]	train-auc:0.99714	eval-auc:0.96418
[232]	train-auc:0.99717	eval-auc:0.96403
[233]	train-auc:0.99719	eval-auc:0.96390
[234]	train-auc:0.99719	eval-auc:0.96390
[235]	train-auc:0.99727	eval-auc:0.96399
[236]	train-auc:0.99729	eval-auc:0.96374
[237]	train-auc:0.99732	eval-auc:0.96368
[238]	train-auc:0.99733	eval-auc:0.96372
[239]	train-auc:0.99736	eval-auc:0.96386
[240]	train-auc:0.99741	eval-auc:0.96387
[241]	train-auc:0.99740	eval-auc:0.96388
[242]	train-auc:0.99743	eval-auc:0.96386
[243]	train-auc:0.99744	eval-auc:0.96386
[244]	train-auc:0.99745	eval-auc:0.96386
[245]	train-auc:0.99750	eval-auc:0.96373
[246]	train-auc:0.99751	eval-auc:0.96386
[247]	train-auc:0.99757	eval-auc:0.96399
[248]	train-auc:0.99758	eval-auc:0.96398
[249]	train-auc:0.99764	eval-auc:0.96409
[250]	train-auc:0.99765	eval-auc:0.96418
[251]	train-auc:0.99765	eval-auc:0.96423
[252]	train-auc:0.99766	eval-auc:0.96423
[253]	train-auc:0.99774	eval-auc:0.96444
[254]	train-auc:0.99777	eval-auc:0.96449
[255]	train-auc:0.99785	eval-auc:0.96456
[256]	train-auc:0.99793	eval-auc:0.96482
[257]	train-auc:0.99793	eval-auc:0.96482
[258]	train-auc:0.99796	eval-auc:0.96487
[259]	train-auc:0.99796	eval-auc:0.96485
[260]	train-auc:0.99797	eval-auc:0.96495
[261]	train-auc:0.99797	eval-auc:0.96495
[262]	train-auc:0.99800	eval-auc:0.96490
[263]	train-auc:0.99800	eval-auc:0.96498
[264]	train-auc:0.99800	eval-auc:0.96498
[265]	train-auc:0.99800	eval-auc:0.96498
[266]	train-auc:0.99807	eval-auc:0.96495
[267]	train-auc:0.99811	eval-auc:0.96497
[268]	train-auc:0.99811	eval-auc:0.96485
[269]	train-auc:0.99810	eval-auc:0.96488
[270]	train-auc:0.99815	eval-auc:0.96506
[271]	train-auc:0.99815	eval-auc:0.96506
[272]	train-auc:0.99815	eval-auc:0.96506
[273]	train-auc:0.99821	eval-auc:0.96518
[274]	train-auc:0.99821	eval-auc:0.96524
[275]	train-auc:0.99826	eval-auc:0.96535
[276]	train-auc:0.99830	eval-auc:0.96521
[277]	train-auc:0.99834	eval-auc:0.96498
[278]	train-auc:0.99837	eval-auc:0.96504
[279]	train-auc:0.99837	eval-auc:0.96504
[280]	train-auc:0.99839	eval-auc:0.96501
[281]	train-auc:0.99840	eval-auc:0.96496
[282]	train-auc:0.99840	eval-auc:0.96486
[283]	train-auc:0.99840	eval-auc:0.96486
[284]	train-auc:0.99844	eval-auc:0.96474
[285]	train-auc:0.99844	eval-auc:0.96474
[286]	train-auc:0.99847	eval-auc:0.96475
[287]	train-auc:0.99848	eval-auc:0.96474
[288]	train-auc:0.99848	eval-auc:0.96474
[289]	train-auc:0.99848	eval-auc:0.96466
[290]	train-auc:0.99850	eval-auc:0.96466
[291]	train-auc:0.99851	eval-auc:0.96445
[292]	train-auc:0.99853	eval-auc:0.96441
[293]	train-auc:0.99854	eval-auc:0.96436
[294]	train-auc:0.99856	eval-auc:0.96436
[295]	train-auc:0.99857	eval-auc:0.96444
[296]	train-auc:0.99857	eval-auc:0.96456
[297]	train-auc:0.99860	eval-auc:0.96465
[298]	train-auc:0.99860	eval-auc:0.96474
[299]	train-auc:0.99860	eval-auc:0.96475
[300]	train-auc:0.99862	eval-auc:0.96475
[301]	train-auc:0.99862	eval-auc:0.96475
[302]	train-auc:0.99865	eval-auc:0.96472
[303]	train-auc:0.99868	eval-auc:0.96492
[304]	train-auc:0.99874	eval-auc:0.96498
[305]	train-auc:0.99874	eval-auc:0.96488
[306]	train-auc:0.99876	eval-auc:0.96466
[307]	train-auc:0.99876	eval-auc:0.96466
[308]	train-auc:0.99876	eval-auc:0.96466
[309]	train-auc:0.99879	eval-auc:0.96464
[310]	train-auc:0.99879	eval-auc:0.96464
[311]	train-auc:0.99879	eval-auc:0.96464
[312]	train-auc:0.99881	eval-auc:0.96444
[313]	train-auc:0.99883	eval-auc:0.96456
[314]	train-auc:0.99883	eval-auc:0.96456
[315]	train-auc:0.99888	eval-auc:0.96490
[316]	train-auc:0.99888	eval-auc:0.96490
[317]	train-auc:0.99888	eval-auc:0.96471
[318]	train-auc:0.99889	eval-auc:0.96474
[319]	train-auc:0.99889	eval-auc:0.96474
[320]	train-auc:0.99889	eval-auc:0.96470
[321]	train-auc:0.99891	eval-auc:0.96465
[322]	train-auc:0.99891	eval-auc:0.96478
[323]	train-auc:0.99891	eval-auc:0.96478
[324]	train-auc:0.99893	eval-auc:0.96498
[325]	train-auc:0.99895	eval-auc:0.96498
[326]	train-auc:0.99895	eval-auc:0.96497
[327]	train-auc:0.99896	eval-auc:0.96518
[328]	train-auc:0.99895	eval-auc:0.96516
[329]	train-auc:0.99896	eval-auc:0.96534
[330]	train-auc:0.99899	eval-auc:0.96532
[331]	train-auc:0.99902	eval-auc:0.96540
[332]	train-auc:0.99903	eval-auc:0.96522
[333]	train-auc:0.99904	eval-auc:0.96529
[334]	train-auc:0.99904	eval-auc:0.96529
[335]	train-auc:0.99904	eval-auc:0.96529
[336]	train-auc:0.99906	eval-auc:0.96532
[337]	train-auc:0.99906	eval-auc:0.96532
[338]	train-auc:0.99906	eval-auc:0.96532
[339]	train-auc:0.99906	eval-auc:0.96532
[340]	train-auc:0.99906	eval-auc:0.96519
[341]	train-auc:0.99906	eval-auc:0.96519
[342]	train-auc:0.99908	eval-auc:0.96508
[343]	train-auc:0.99908	eval-auc:0.96508
[344]	train-auc:0.99908	eval-auc:0.96508
[345]	train-auc:0.99908	eval-auc:0.96501
[346]	train-auc:0.99908	eval-auc:0.96501
[347]	train-auc:0.99908	eval-auc:0.96501
[348]	train-auc:0.99908	eval-auc:0.96501
[349]	train-auc:0.99908	eval-auc:0.96501
[350]	train-auc:0.99908	eval-auc:0.96506
[351]	train-auc:0.99909	eval-auc:0.96516
[352]	train-auc:0.99909	eval-auc:0.96516
[353]	train-auc:0.99911	eval-auc:0.96521
[354]	train-auc:0.99911	eval-auc:0.96521
[355]	train-auc:0.99912	eval-auc:0.96514
[356]	train-auc:0.99913	eval-auc:0.96521
[357]	train-auc:0.99916	eval-auc:0.96518
[358]	train-auc:0.99916	eval-auc:0.96518
[359]	train-auc:0.99916	eval-auc:0.96518
[360]	train-auc:0.99916	eval-auc:0.96518
[361]	train-auc:0.99916	eval-auc:0.96521
[362]	train-auc:0.99916	eval-auc:0.96521
[363]	train-auc:0.99916	eval-auc:0.96521
[364]	train-auc:0.99918	eval-auc:0.96513
[365]	train-auc:0.99918	eval-auc:0.96513
[366]	train-auc:0.99918	eval-auc:0.96513
[367]	train-auc:0.99919	eval-auc:0.96523
[368]	train-auc:0.99919	eval-auc:0.96523
[369]	train-auc:0.99919	eval-auc:0.96523
[370]	train-auc:0.99920	eval-auc:0.96525
[371]	train-auc:0.99922	eval-auc:0.96534
[372]	train-auc:0.99922	eval-auc:0.96530
[373]	train-auc:0.99922	eval-auc:0.96530
[374]	train-auc:0.99922	eval-auc:0.96528
[375]	train-auc:0.99923	eval-auc:0.96538
[376]	train-auc:0.99924	eval-auc:0.96543
[377]	train-auc:0.99925	eval-auc:0.96555
[378]	train-auc:0.99925	eval-auc:0.96555
[379]	train-auc:0.99925	eval-auc:0.96552
[380]	train-auc:0.99924	eval-auc:0.96538
[381]	train-auc:0.99924	eval-auc:0.96532
[382]	train-auc:0.99925	eval-auc:0.96521
[383]	train-auc:0.99925	eval-auc:0.96521
[384]	train-auc:0.99926	eval-auc:0.96516
[385]	train-auc:0.99926	eval-auc:0.96516
[386]	train-auc:0.99926	eval-auc:0.96516
[387]	train-auc:0.99926	eval-auc:0.96516
[388]	train-auc:0.99926	eval-auc:0.96516
[389]	train-auc:0.99926	eval-auc:0.96516
[390]	train-auc:0.99926	eval-auc:0.96516
[391]	train-auc:0.99926	eval-auc:0.96513
[392]	train-auc:0.99926	eval-auc:0.96513
[393]	train-auc:0.99928	eval-auc:0.96513
[394]	train-auc:0.99929	eval-auc:0.96512
[395]	train-auc:0.99930	eval-auc:0.96508
[396]	train-auc:0.99931	eval-auc:0.96508
[397]	train-auc:0.99932	eval-auc:0.96514
[398]	train-auc:0.99933	eval-auc:0.96516
[399]	train-auc:0.99934	eval-auc:0.96521
[400]	train-auc:0.99934	eval-auc:0.96521
[401]	train-auc:0.99934	eval-auc:0.96521
[402]	train-auc:0.99934	eval-auc:0.96521
[403]	train-auc:0.99934	eval-auc:0.96521
[404]	train-auc:0.99934	eval-auc:0.96521
[405]	train-auc:0.99934	eval-auc:0.96522
[406]	train-auc:0.99934	eval-auc:0.96522
[407]	train-auc:0.99934	eval-auc:0.96522
[408]	train-auc:0.99934	eval-auc:0.96522
[409]	train-auc:0.99935	eval-auc:0.96508
[410]	train-auc:0.99936	eval-auc:0.96511
[411]	train-auc:0.99936	eval-auc:0.96511
[412]	train-auc:0.99936	eval-auc:0.96511
[413]	train-auc:0.99936	eval-auc:0.96511
[414]	train-auc:0.99936	eval-auc:0.96511
[415]	train-auc:0.99936	eval-auc:0.96511
[416]	train-auc:0.99936	eval-auc:0.96511
[417]	train-auc:0.99936	eval-auc:0.96511
[418]	train-auc:0.99936	eval-auc:0.96511
[419]	train-auc:0.99936	eval-auc:0.96511
[420]	train-auc:0.99936	eval-auc:0.96491
[421]	train-auc:0.99937	eval-auc:0.96487
[422]	train-auc:0.99937	eval-auc:0.96487
[423]	train-auc:0.99937	eval-auc:0.96487
[424]	train-auc:0.99938	eval-auc:0.96485
[425]	train-auc:0.99938	eval-auc:0.96474
[426]	train-auc:0.99937	eval-auc:0.96476
[427]	train-auc:0.99937	eval-auc:0.96476
[428]	train-auc:0.99937	eval-auc:0.96476
[429]	train-auc:0.99938	eval-auc:0.96487
[430]	train-auc:0.99939	eval-auc:0.96495
[431]	train-auc:0.99939	eval-auc:0.96495
[432]	train-auc:0.99938	eval-auc:0.96497
[433]	train-auc:0.99938	eval-auc:0.96497
[434]	train-auc:0.99939	eval-auc:0.96498
[435]	train-auc:0.99939	eval-auc:0.96503
[436]	train-auc:0.99939	eval-auc:0.96508
[437]	train-auc:0.99940	eval-auc:0.96497
[438]	train-auc:0.99940	eval-auc:0.96492
[439]	train-auc:0.99940	eval-auc:0.96498
[440]	train-auc:0.99941	eval-auc:0.96493
[441]	train-auc:0.99941	eval-auc:0.96500
[442]	train-auc:0.99941	eval-auc:0.96500
[443]	train-auc:0.99941	eval-auc:0.96500
[444]	train-auc:0.99942	eval-auc:0.96501
[445]	train-auc:0.99942	eval-auc:0.96501
[446]	train-auc:0.99942	eval-auc:0.96501
[447]	train-auc:0.99942	eval-auc:0.96501
[448]	train-auc:0.99942	eval-auc:0.96501
[449]	train-auc:0.99943	eval-auc:0.96488
[450]	train-auc:0.99943	eval-auc:0.96488
[451]	train-auc:0.99943	eval-auc:0.96488
[452]	train-auc:0.99943	eval-auc:0.96488
[453]	train-auc:0.99943	eval-auc:0.96488
[454]	train-auc:0.99943	eval-auc:0.96497
[455]	train-auc:0.99943	eval-auc:0.96497
[456]	train-auc:0.99944	eval-auc:0.96496
[457]	train-auc:0.99945	eval-auc:0.96498
[458]	train-auc:0.99945	eval-auc:0.96498
[459]	train-auc:0.99945	eval-auc:0.96498
[460]	train-auc:0.99945	eval-auc:0.96498
[461]	train-auc:0.99945	eval-auc:0.96498
[462]	train-auc:0.99946	eval-auc:0.96501
[463]	train-auc:0.99946	eval-auc:0.96501
[464]	train-auc:0.99946	eval-auc:0.96493
[465]	train-auc:0.99946	eval-auc:0.96493
[466]	train-auc:0.99946	eval-auc:0.96493
[467]	train-auc:0.99946	eval-auc:0.96501
[468]	train-auc:0.99946	eval-auc:0.96496
[469]	train-auc:0.99946	eval-auc:0.96496
[470]	train-auc:0.99946	eval-auc:0.96496
[471]	train-auc:0.99946	eval-auc:0.96496
[472]	train-auc:0.99946	eval-auc:0.96496
[473]	train-auc:0.99946	eval-auc:0.96496
[474]	train-auc:0.99947	eval-auc:0.96498
[475]	train-auc:0.99947	eval-auc:0.96498
[476]	train-auc:0.99947	eval-auc:0.96507
[477]	train-auc:0.99947	eval-auc:0.96507
Stopping. Best iteration:
[377]	train-auc:0.99925	eval-auc:0.96555

In [237]:
# model.get_score()

In [238]:
def best_f1(val_y,y_pred_pro):
    f1_list = []
    threshold = np.arange(0.4,0.7,0.01)
    for i in threshold:
        y_pred = (y_pred_pro >= i) * 1
        f1 = metrics.f1_score(val_y,y_pred)
        f1_list.append(f1)
    index = np.argmax(f1_list)
    best_f1 = max(f1_list)
    return threshold[index], best_f1

In [239]:
y_pred_pro = model.predict(dval)

In [240]:
p, f1 = best_f1(val_y, y_pred_pro)

In [241]:
print(p,f1)

0.6900000000000003 0.935483870967742

In [242]:
test_df.drop(['label'], axis = 1,inplace = True)

F:\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [243]:
test_df.columns[test_df.isnull().any()]

Index([], dtype='object')

In [246]:
dtest = xgb.DMatrix(test_df, label =None)

In [247]:
y_pred = model.predict(dtest)
y_pred = (y_pred >=p) * 1

In [248]:
y_pred = pd.DataFrame(y_pred)
y_pred.to_csv('./submit.csv',encoding = 'utf-8')

In [249]:
y_pred

      0
0     1
1     1
2     0
3     0
4     0
...  ..
2040  0
2041  0
2042  0
2043  0
2044  1

[2045 rows x 1 columns]